---
name: "Checks"
on:
  push:
    branches:
      - "main"
      - "develop"

jobs:
  test-lint:
    name: "Lint and Test"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Login to Docker Hub"
        uses: "docker/login-action@v1"
        with:
          username: "${{ secrets.DOCKERHUB_USER }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Linting: flake8"
        run: "docker-compose run --rm app sh -c 'flake8'"
      - name: "Waint for DB" 
        run: "docker-compose run --rm app sh -c 'python manage.py wait_for_db'"
      - name: "Run Unit Tests" 
        run: "docker-compose run --rm app sh -c 'python manage.py test'"
